// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmjghbyryxzqkirzfxsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtamdoYnlyeXh6cWtpcnpmeHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Njc1NzEsImV4cCI6MjA2NzA0MzU3MX0.73cFvfDp9xcdv6dv6DsUUJBt6kNC1E5yn1AF44DrPGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});